### ISSUE TITLE
这是pc版的mod对应表，求一个quest版的对应表

### ISSUE THREAD

**Issue by tomcat-bj** [wgzeyu/BeatSaberModListTranslationRepo#1]
大佬辛苦啦，quest里的很多mod在这里找不到，对于光剑爱好者+英文苦手来说，实在是一件很痛苦的事

**Comment by WGzeyu** [comment]
这个是中文版ModAssistant调用的翻译表，而Quest还没有类似的软件，就是做了翻译也不能替换到界面上，所以目前不打算制作。
Quest端算得上类似的只有QuestModding网站，因为是网页端，所以可以靠网页翻译实现类似的效果。

**Comment by tomcat-bj** [comment]
好的，在大佬的网站上学到很多光剑技巧，下到很多很好的资源，不知大佬是否可以做一个或者推荐一个介绍常用mod的中文页面呢，感谢感恩大佬的辛勤付出

**Comment by WGzeyu** [comment]
如果是quest的推荐mod，前几天已经更新到教程里了

**Comment by tomcat-bj** [comment]
嗯……是在 安装Mod 下面吧，那个已经记下了。我下了个懒人包，里面大量mod不知道干嘛用……mod下的英文介绍也有些云里雾里，按照名称有些能搜到中文介绍，多数找不到，能麻烦大佬指个路吗

**Comment by WGzeyu** [comment]
如果是quest版本懒人包，你应该找做懒人包的人问。

**Comment by WGzeyu** [comment]
questmodding网页打开后，可以右键翻译为中文

**Comment by tomcat-bj** [comment]
……下的地方没有留言功能……，好吧，我还是啃硬翻+多实验吧，google搜索questmodding，找到三个网站，不确定哪个是正牌，麻烦发一下地址吧，谢啦

**Comment by WGzeyu** [comment]
教程里有questmodding的链接，为什么不看教程？[https://bs-wgzeyu.gtxcn.com/oq-guide/](https://bs-wgzeyu.gtxcn.com/oq-guide/)  
另外，questmodding网站地址，其实就是questmodding后面加上个.com（[questmodding.com](https://www.questmodding.com/)）

**Comment by tomcat-bj** [comment]
惭愧，看了好几天教程，还是把这里疏漏了。另外……发现这个网站我从您的教程点进去过，当时看到Beat Saber 1.17.1 has Released!第一反应以为是光剑官网退出了

**Comment by WGzeyu** [comment]
https://github.com/WGzeyu/QuestModInfoLocalization/blob/main/README.md
